#!/bin/bash 

base="http://localhost:8080"

function get {
	url="$base$1"
	echo $'\n'"HTTP GET from $url:"
	echo '----'
	curl -i $url
	echo $'\n----'
}

function post {
	url="$base$1"
	echo $'\n'"HTTP POST of $2 to $url:"
	echo '----'
	curl -i $url -d "$2" -H "Content-Type: application/json"
	echo $'\n----'
}

get /openapi

get /health
get /metrics

get  /greetings
get  /greetings/
get  /greetings/Gerald
post /greetings '{"name":"Gerald"}'
get  /greetings/Gerald
post /greetings '{"name":"gerald"}'
get  /greetings/gerald
get  /greetings
